# Generated manually for Meubles RD mockup

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('nom_du_compte', models.CharField(blank=True, max_length=200)),
                ('adresse_email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('telephone_mobile', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Requete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('proprietaire', models.CharField(default='', max_length=200)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_traitement', 'En traitement'), ('en_attente_client', 'En attente du client'), ('en_suspens', 'En suspens'), ('ferme', 'Fermé')], default='nouveau', max_length=30)),
                ('priorite', models.CharField(choices=[('bas', 'Bas'), ('moyen', 'Moyen'), ('haut', 'Haut')], default='moyen', max_length=20)),
                ('objet', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('date_ouverture', models.DateTimeField(blank=True, null=True)),
                ('date_fermeture', models.DateTimeField(blank=True, null=True)),
                ('magasin', models.CharField(blank=True, max_length=200)),
                ('requete_principale', models.CharField(blank=True, max_length=100)),
                ('lead_id', models.CharField(blank=True, max_length=100)),
                ('origine', models.CharField(blank=True, max_length=100)),
                ('origine_requete', models.CharField(blank=True, max_length=100)),
                ('suiveur', models.CharField(blank=True, max_length=200)),
                ('cc_courriel', models.CharField(blank=True, max_length=200)),
                ('classification', models.CharField(blank=True, max_length=200)),
                ('sous_sujet', models.CharField(blank=True, max_length=200)),
                ('type_requete_client_interne', models.CharField(blank=True, max_length=200)),
                ('sujet_livraison_interne', models.CharField(blank=True, max_length=200)),
                ('sujet_ads_interne', models.CharField(blank=True, max_length=200)),
                ('avis_formel', models.CharField(blank=True, max_length=200)),
                ('numero_contrat_achat', models.CharField(blank=True, max_length=50)),
                ('manufacturier', models.CharField(blank=True, max_length=200)),
                ('code_produit', models.CharField(blank=True, max_length=50)),
                ('type_produit', models.CharField(blank=True, max_length=100)),
                ('no_serie_appareil', models.CharField(blank=True, max_length=100)),
                ('type_achat', models.CharField(blank=True, max_length=100)),
                ('no_requete_a_suivre', models.CharField(blank=True, max_length=50)),
                ('ads_need_type', models.CharField(blank=True, max_length=100)),
                ('envoyer_courriel_contact', models.BooleanField(default=False)),
                ('commentaires_internes', models.TextField(blank=True)),
                ('modification_sms', models.TextField(blank=True)),
                ('type_reception', models.CharField(blank=True, max_length=100)),
                ('region_livraison', models.CharField(blank=True, max_length=200)),
                ('no_compte_client_meublex', models.CharField(blank=True, max_length=100)),
                ('date_livraison', models.DateField(blank=True, null=True)),
                ('ajustement_contrat', models.CharField(blank=True, max_length=50)),
                ('capacite_cubage', models.CharField(blank=True, max_length=100)),
                ('plage_horaire_desiree', models.CharField(blank=True, max_length=200)),
                ('changement_contrat_bloque', models.CharField(blank=True, max_length=100)),
                ('instructions_speciales', models.TextField(blank=True)),
                ('numero_ads', models.CharField(blank=True, max_length=50)),
                ('solution', models.TextField(blank=True)),
                ('information_additionnelle', models.TextField(blank=True)),
                ('type_dommage', models.CharField(blank=True, max_length=200)),
                ('type_compensation', models.CharField(blank=True, max_length=100)),
                ('montant_dedommagement', models.CharField(blank=True, max_length=50)),
                ('numero_lot', models.CharField(blank=True, max_length=50)),
                ('code_production', models.CharField(blank=True, max_length=50)),
                ('preference_communication', models.CharField(blank=True, max_length=200)),
                ('contrat_livraison_interne', models.BooleanField(default=False)),
                ('nom_web', models.CharField(blank=True, max_length=200)),
                ('telephone_web', models.CharField(blank=True, max_length=50)),
                ('prenom_client', models.CharField(blank=True, max_length=100)),
                ('nom_client', models.CharField(blank=True, max_length=100)),
                ('nom_complet_client', models.CharField(blank=True, max_length=200)),
                ('courriel_client', models.EmailField(blank=True, max_length=254)),
                ('telephone_client', models.CharField(blank=True, max_length=50)),
                ('arrete', models.BooleanField(default=False)),
                ('arrete_depuis', models.CharField(blank=True, max_length=100)),
                ('nom_autorisation_sla', models.CharField(blank=True, max_length=200)),
                ('nombre_total_produits_defectueux', models.PositiveIntegerField(default=0)),
                ('solution_derniere_modification_par', models.CharField(blank=True, max_length=300)),
                ('courriel_envoye_a', models.CharField(blank=True, max_length=300)),
                ('cree_par', models.CharField(blank=True, max_length=200)),
                ('type_besoin', models.CharField(blank=True, max_length=100)),
                ('derniere_file_attente', models.CharField(blank=True, max_length=200)),
                ('nombre_produits_defectueux_ouverts', models.PositiveIntegerField(default=0)),
                ('depuis_le_web', models.BooleanField(default=False)),
                ('fermeture_lors_creation', models.BooleanField(default=False)),
                ('langue', models.CharField(default='Français', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requetes', to='tickets.contact')),
            ],
            options={
                'verbose_name': 'Requête',
                'verbose_name_plural': 'Requêtes',
                'ordering': ['-date_ouverture', '-created_at'],
            },
        ),
    ]
