# Generated by Django 5.2.11 on 2026-02-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requete',
            name='purchase_contract_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='requete',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
